### PR TITLE
Get RL9.5 working for non-OFED slurm builds

### PR DESCRIPTION
**Pull request by bertiethorpe**
```
TASK [mysql : Pull container image] ********************************************
Monday 25 November 2024  16:48:12 +0000 (0:00:03.710)       0:05:07.831 ******* 
fatal: [slurmci-RL9-1579-control]: FAILED! => {
    "changed": false
}

MSG:

Failed to pull image docker.io/library/mysql:8.0.30
```

### CODE REVIEW

**Comment by bertiethorpe** [comment]
fatimages: https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/12010050553

**Comment by bertiethorpe** [comment]
fatimage:
https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/12011386383

**Review by sjpb — COMMENTED** [review]
LGTM; not merging right now b/c we don't want to override our current RL9.4 image, given we can't build OFED for 9.5 at all. PR will be marked as draft.

**Comment by wtripp180901** [comment]
can probably be replaced with https://github.com/stackhpc/ansible-slurm-appliance/pull/503

**Comment by sjpb** [comment]
Note when bumping to RL9.5 it'll need `appliances_repo_timestamps` in environments/common/inventory/group_vars/all/defaults.yml moving to appropriate/latest RL9.5 snapshots

**Comment by sjpb** [comment]
Replaced by https://github.com/stackhpc/ansible-slurm-appliance/pull/503

**Pull request closed without merging**
