### PR TITLE
Image update - OpenHPC v3.1 for RL9

### PR DESCRIPTION
**Pull request by sjpb**
- RL9.4
- OpenHPC v3.1 (bumps slurm from 22.0.5 to 23.11.5, new compilers etc)
- Upgrades OFED to version `24.04-0.6.6.0`
- Bumps OSC ondemand role, so the dnf-installed ondemand package will now be the latest available.
- Makes CI run RL8 automatically if PR is labelled with "RL8"

NB: both ofed and non-ofed images now require 15GB root disks.

### CODE REVIEW

**Comment by sjpb** [comment]
Image build for RL8 and RL9: https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/9204915185

**Comment by sjpb** [comment]
Image build: https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/9220886576

**Comment by sjpb** [comment]
Image build: https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/9221454393

**Comment by sjpb** [comment]
Image build: https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/9267920121

**Comment by sjpb** [comment]
Image build: https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/9272374302

**Comment by sjpb** [comment]
Image build: https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/9282231244

**Comment by sjpb** [comment]
Image build: https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/9283876532

**Comment by sjpb** [comment]
Image build: https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/9287616135

**Comment by sjpb** [comment]
Image update: https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/9364254078

**Comment by sjpb** [comment]
Image update https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/9365105456

**Comment by sjpb** [comment]
Image build: https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/9369610573

**Comment by sjpb** [comment]
Image build: https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/9370488867

**Comment by sjpb** [comment]
Image build: https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/9381036201

**Comment by sjpb** [comment]
Image build: https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/9383705314

**Comment by sjpb** [comment]
RL9 manual tests on OOD:
- shell OK
- desktop: OK
- jupyter: OK
- monitoring: OK

**Comment by sjpb** [comment]
Leafcloud pingpong:
image
vs previous release image:
image

**Review by m-bull — APPROVED** [review]
LGTM

**Pull request merged**
