### PR TITLE
EXPERIMENTAL: add machinery to allow compute nodes to rejoin cluster on reimage

### PR DESCRIPTION
**Pull request by sjpb**
Uses ansible-init playbook added to the image to allow compute nodes to rejoin the cluster after reimage.

See the `compute_init` role  for full details. At this PR it supports the following roles/functionality:
- `resolv_conf`: all functionality
- `etc_hosts`: all functionality
- `nfs`: client functionality only
- `manila`: all functionality
- `basic_users`: all functionality, assumes home directory already exists on
  shared storage
- `eessi`: all functionality, assumes `cvmfs_config` is the same on control
  node and all compute nodes.
- `openhpc`: all functionality

While this functionality is added to the image, it is not enabled by default in any environments.

### CODE REVIEW

**Comment by sjpb** [comment]
Image build: https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/12372688154

**Comment by sjpb** [comment]
image build ghttps://github.com/stackhpc/ansible-slurm-appliance/actions/runs/12377489377

**Comment by sjpb** [comment]
Tested on arcus (with manila) with everything enabled, without actually having compute-init in the image.
- run site
- reimage compute
- run build to install compute-init machinery
- restart ansible-init

check:
- /etc/resolv.conf
- /etc/hosts
- df -h /home # is nfs
- df -h /project # is manila
- df -h /scratch # is manila
- id testuser
- sinfo

**Comment by sjpb** [comment]
Tested on arcus (with manila) with everything enabled, without actually having compute-init in the image.
- run site
- reimage compute
- run build to install compute-init machinery
- restart ansible-init

check:
- /etc/resolv.conf
- /etc/hosts
- df -h /home # is nfs
- df -h /project # is manila
- df -h /scratch # is manila
- id testuser
- sinfo

**Comment by sjpb** [comment]
Also tested with only enable_compute and enable_etc_hosts turned on, worked too.

**Comment by bertiethorpe** [comment]
successfully tested no-op/metadata toggling with new image

**Review by bertiethorpe — APPROVED** [review]
Tested and ready to merge

**Pull request merged**
