### PR TITLE
Update to Open OnDemand v3.0.1

### PR DESCRIPTION
**Pull request by sjpb**
Update to Open OnDemand v3.0.1, provided by @thomasbergernz

### CODE REVIEW

**Comment by sjpb** [comment]
TODO: requires manual checks on OOD

**Comment by sjpb** [comment]
Running new fat image build: https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/6313561262/job/17141887613

**Comment by sjpb** [comment]
Manual checks on OOD ok on local deployment as of above commit:
- OOD up OK
- files app - works
- shell app - works
- desktop app - works
- jupyter app - works
- monitoring - works, can see slurm jobs in dashboard

**Review by sd109 — APPROVED** [review]
LGTM

**Pull request merged**
