### PR TITLE
Add CI for OOD

### PR DESCRIPTION
**Pull request by sjpb**
Open Ondemand is already setup in the `smslabs-example` environment in the `ood` branch. This adds a task to check the OOD server returns 200. Bit complicated due to this requiring a SOCKS proxy to get to.

NB: relies on both:
- #101 
- #155

### CODE REVIEW

**Comment by sjpb** [comment]
@m-bull this is queued in CI - if it happens to pass first time perhaps you could remove draft label and review?

**Comment by sjpb** [comment]
@m-bull ready for review.

**Comment by sjpb** [comment]
@m-bull all dependencies merged for this.

**Review by m-bull — APPROVED** [review]
I don't see anything egregious!

**Pull request merged**
