### PR TITLE
Support Rocky 8.5

### PR DESCRIPTION
**Pull request by sjpb**
Non-backward compatible change - `environments/common/inventory/group_vars/all/defaults.yml` `ansible_user: centos` is now `rocky`.

Other PRs which are required for this:
- [ ] https://github.com/stackhpc/ansible-role-openhpc/pull/125
- [ ] https://github.com/cloudalchemy/ansible-prometheus/pull/366
- [ ] https://github.com/cloudalchemy/ansible-node-exporter/pull/247

Repo: alarc-deploy2:/home/centos/alarc-slurm-dev/environments/vagrant-example @feature/Rocky

### CODE REVIEW

**Comment by sjpb** [comment]
Also need to consider changing packer build image

**Comment by sjpb** [comment]
I think the CI failure on this is just because I (deliberately) didn't change the openhpc role to the rocky-compatible one. Will hit same problem with prometheus too.

**Comment by sjpb** [comment]
TODO: should try deploying appliance and running vagrant from a Rocky 8.5 host

**Comment by sjpb** [comment]
Tested on smslabs openstack. Can deploy, configure and run hpctests ok.

In github Vagrant CI there is a consistent error that ansible can't connect to the control node.

Running Vagrant locally, that error doesn't occur but pingpong hangs after completing the actual tests. `strace` showed an openmpi process was sleeping after a `restart_syscall`.

**Comment by sjpb** [comment]
Ran packer/vagrant build and redeployed (via TF) login + compute nodes. Had to restart slurm daemons but then ran openhpc tests ok.

**Review by jovial — APPROVED** [review]
All looks sensible to me. I believe the plan was to merge in the CI branch before merging.

**Pull request merged**
