### PR TITLE
Add description of image to build

### PR DESCRIPTION
**Pull request by sjpb**
Provides `/var/lib/image/image.json` describing important package versions etc.

### CODE REVIEW

**Comment by sjpb** [comment]
build: https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/11069089483

**Comment by sjpb** [comment]
build: https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/11140775153

**Comment by sjpb** [comment]
build: https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/11147496135

**Review by sd109 — APPROVED** [review]
LGTM

**Pull request merged**
